version: 2.1

orbs:
  yarn: artsy/yarn@4.0.2
  auto: artsy/auto@1.2.0
  aws-s3: circleci/aws-s3@1.0.15

jobs:
  upload-docs:
    docker:
      - image: "cimg/python:3.6"
    steps:
      - aws-s3/sync:
          arguments: --acl public-read
          from: doc
          to: "s3://artsy-static-sites/artsy-cohesion"

deploy: &deploy
  context: npm-deploy
  pre-steps:
    - yarn/run-script:
        script: compile

not_master: &not_master
  filters:
    branches:
      ignore: master

only_master: &only_master
  filters:
    branches:
      only: master

workflows:
  build_and_verify:
    jobs:
      - yarn/run:
          name: build-docs
          script: "docs"
          post-steps:
            - persist_to_workspace:
                root: .
                paths:
                  - doc
      - upload-docs:
          context: static-sites-uploader
          requires:
            - build-docs
          pre-steps:
            - attach_workspace:
                at: .
      - yarn/workflow-queue
      - yarn/update-cache:
          requires:
            - yarn/workflow-queue
      - yarn/type-check:
          requires:
            - yarn/workflow-queue
      - yarn/jest:
          args: --runInBand
      # Pr builds
      - auto/publish-canary:
          <<: *not_master
          <<: *deploy
          requires:
            - yarn/jest
            - yarn/type-check
            - yarn/update-cache
      # Releases
      - auto/publish:
          <<: *only_master
          <<: *deploy
          requires:
            - yarn/jest
            - yarn/type-check
            - yarn/update-cache
            - build-docs
