version: 2.1

orbs:
  yarn: artsy/yarn@4.0.2
  auto: artsy/auto@1.2.0

deploy: &deploy
  context: npm-deploy
  pre-steps:
    - yarn/run-script:
        script: compile

not_master: &not_master
  filters:
    branches:
      ignore: master

only_master: &only_master
  filters:
    branches:
      only: master

workflows:
  build_and_verify:
    jobs:
      - yarn/workflow-queue
      - yarn/update-cache:
          requires:
            - yarn/workflow-queue
      - yarn/type-check:
          requires:
            - yarn/workflow-queue
      - yarn/jest:
          args: --runInBand
      # Pr builds
      - auto/publish-canary:
          <<: *not_master
          <<: *deploy
          requires:
            - yarn/jest
            - yarn/type-check
            - yarn/update-cache
      # Releases
      - auto/publish:
          <<: *only_master
          <<: *deploy
          requires:
            - yarn/jest
            - yarn/type-check
            - yarn/update-cache
