version: 2.1

orbs:
  yarn: artsy/yarn@4.0.2
  auto: artsy/auto@dev:a330f60962eae103f5c839f4eee0c18a

not_master: &not_master
  context: npm-deploy
  filters:
    branches:
      ignore: master

only_master: &only_master
  context: npm-deploy
  filters:
    branches:
      only: master

workflows:
  build_and_verify:
    jobs:
      - yarn/workflow-queue
      - yarn/update-cache:
          requires:
            - yarn/workflow-queue
      - yarn/type-check:
          requires:
            - yarn/workflow-queue
      - yarn/jest:
          args: --runInBand
      # Pr builds
      - auto/publish-canary:
          <<: *not_master
          requires:
            - yarn/jest
            - yarn/type-check
            - yarn/update-cache
      # Releases
      - auto/publish:
          <<: *only_master
          requires:
            - yarn/jest
            - yarn/type-check
            - yarn/update-cache
